name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up C++ environment
      uses: actions/setup-cpp@v1
      with:
        compiler: g++ 
        run-version-check: true 

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

    - name: Build project
      run: cmake --build build -- -j$(nproc)

    - name: Run executables
      run: |
        for exe in build/*; do
          if [[ -x "$exe" ]]; then
            echo "Running $exe:"
            $exe
          fi
        done
